---
# Execute required configurations to headless server
- name: copy config files
  ansible.builtin.template:
    src: "headless.json.j2"
    dest: "/etc/resilio-sync/config.json"
    owner: root
    group: root

- name: restart resilio service
  ansible.builtin.service:
    name: resilio-sync
    state: restarted
    enabled: yes

- name: config owners for specified folders
  ansible.builtin.file:
    path: "{{ item.dir }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ folder_owner_n_mode | list}}"
