---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bullseye
    image: debian:11
    pre_build_image: false
  - name: jammy
    image: ubuntu:22.04
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
