---
name: Molecule Test
on: [push, pull_request]
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: '${GITHUB_REPOSITORY}'