---
name: Molecule Test
on: [push, pull_request]
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test path
        run: |
          pwd
          ls
          echo ---
          ls ..
          echo ---
      - uses: gofrolist/molecule-action@v2